# Generated by Django 2.2 on 2021-10-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItem',
            new_name='UserProfileFeedItem',
        ),
    ]
